-- MySQL Script generated by MySQL Workbench
-- Sun May  9 11:52:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema criptome
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema criptome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `criptome` DEFAULT CHARACTER SET utf8 ;
USE `criptome` ;

-- -----------------------------------------------------
-- Table `criptome`.`criptomoedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criptome`.`criptomoedas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `apiID` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `criptome`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criptome`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `criptome`.`users_has_criptomoedas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `criptome`.`users_has_criptomoedas` (
  `users_id` INT NOT NULL,
  `criptomoedas_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `criptomoedas_id`),
  INDEX `fk_Usuarios_has_criptomoedas_criptomoedas1_idx` (`criptomoedas_id` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_criptomoedas_Usuarios_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_criptomoedas_Usuarios`
    FOREIGN KEY (`users_id`)
    REFERENCES `criptome`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_criptomoedas_criptomoedas1`
    FOREIGN KEY (`criptomoedas_id`)
    REFERENCES `criptome`.`criptomoedas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
